name: bengali-matra-decompose
GENERATOR: hb-view
FONT: TiroBangla-Regular.ttf
basecolor: #000000
components:
- before:
    unicodes: 09cc
    margin: 2,16,2,16
    features: -init
- right-arrow:
    file: right-arrow.svg
- after:
    unicodes: 09c7,200c,25cc,09d7
    margin: 2,16,2,16
    features: -init
cssclasses: c0, dc, c0, arrow, c1, dc, dc, dc, c2
