#!/usr/bin/python3
# SPDX-FileCopyrightText: Copyright 2026 Nathan Willis
#
# SPDX-License-Identifier: BSD-2-Clause
"""Build tool for SVG illustrations in the shaping-documents repository.
"""

import sys
import yaml
from lxml import etree as ET
from pathlib import Path

import vharfbuzz as vh
#import svg_stack as ss ## now loading on-demand

CSS_CLASSLIST = ["c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "dc", "arrow"]
"""A list of the known CSS classes applied for SVG illustration interactivity."""

# Margin value of hb-view is in points (1/72 in)
# https://github.com/harfbuzz/harfbuzz/issues/1186#issuecomment-424780696
#
# CSS pixels are 1/96 in
# https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/length#absolute_length_units
#
# :. (72 / 96)pt = 1px
# pix_margin = pt_margin * (96/72)
def hb_pt_to_px(points):
    """Convert lengths in points to the equivalent in pixels."""
    return points * (72 / 96)


def hb_px_to_pt(pixels):
    """Convert lengths in pixels to the equivalent in points."""
    return pixels * (96 / 72)

# Order of arguments
# name,
#  config["GENERATOR"],
#  config["FONT"],
#  config["unicodes"],
#  config["margin"],
#  config["features"],
#  config["options"],                                                    
#  )]

class svgComponent():
    """An individual SVG component within a full illustration.

    Here, "individual component" essentially means a image that can be
    generated by a single command. The full illustration typically consists
    of several individual components that cannot be built all at once
    because they require different feature settings, margins, or perhaps
    different source fonts.

    See also svgFileComponent, which represents the simpler case of an
    individual component that can be read from an external file and does
    not require generation.
    """
     def __init__(self,
                  name,
                  font,
                  unicodes,
                  margin,
                  features=None,
                  options=None,
                  generator="hb-view",
                  basecolor="000000",
                  ):
         self.name = name # or just suffix?
         self.tree = None # May not be needed; initializing to None just so that the attribute is always there upstream
         self.root = None # Also may not be needed; root is gettable from tree
#
         self.font = font
         self.unicodes = unicodes
         self.margin = margin
         self.features = features
         self.options = options # test for None?
         self.generator = generator
         self.basecolor = basecolor
#         
         return None
#
    # I think we want this function to build the SVG and assign it to self.tree
     def generate(self):
         """Generate a fresh instance of the SVG component from its configuration.

         This calls out to the system to execute `self.generator`, so if the configred
         generator program is not found, the generation will fail. A simple test is
         currently used that is expected to behave reasonably on Linux and Linuxy OSes.

         At present, the only generator supported in `hb-view`. Support for any new
         generators should be added here (or, at least, started here).
         """
         import sys # not needed; should be loaded from package
         import shutil
         import subprocess
#
         # test that self.generator exists
         print(f'Checking for the presence of image generator: {self.generator}', file=sys.stderr)
         if not shutil.which(self.generator):
             raise Exception(f'The component generator {self.generator} cannot be found in the system.')
         else:
             # build the command
             command = [f'{self.generator}',
                        "--output-format=svg",            # generates SVG output, and sends it to stdout
                        f'--margin={self.margin}',
                        f'--features={self.features}',
                        f'--foreground={self.basecolor}',
                        f'--background=FFFFFF00',         # for now, make this transparent
                        f'{self.font}',                   # must come next-to-last
                        f'--unicodes={self.unicodes}',    # must come last
                        ]
#
             # call the command, capturing the results from stdout
             result = subprocess.run(command, capture_output=True, encoding="utf8")
             #result = subprocess.run(command, stdout=subprocess.PIPE)
#
         # capture any errors and raise them as exceptions from stderr?
         return result.stdout


     def assign_id(): # Not here, do in Illustration
         return None

     
     def add_viewbox(): # To insert the viewbox ... Not here, do in Illustration
         return None

     def write(filename=None): # To write to an intermediate file
         if filename:
             pass # write to the given filename if asked to...
         else:
             pass # otherwise, write to "{self.name}.svg.in"
             

class svgFileComponent(svgComponent):
    """Simple SVG component class for constituents that can be loaded directly from file.

    The original use case for this is the `right-arrow.svg` component, which is
    used in almost every illustration and (in the present understanding of things)
    needs to be identical in every case. Loading each instance from file reduces
    the need to regenerate a new, identical copy for every illustration.
    """
    def __init__(self,
                 name,
                 filepath):
        self.name = name
        self.file = filepath

        return None

    
    def generate(self):
        namespace = "{http://www.w3.org/2000/svg}"
        
        with open(filepath, 'r+t', encoding='utf-8') as svgfile:
            self.tree = ET.parse(svgfile)
            self.root = self.tree.getroot()

        return self.tree

    
class Illustration():
    """An SVG illustration. Each illustration is defined in a YAML file that specifies some basic properties
       and, typically, a list of components that must be individually generated as intermediate images.

       For example, there is usually a "-before" and "-after" variant of a shaping cluster, which require two
       separate commands and parameter sets to generate. The two are then typically composited into the final
       illustration with an 'arrow' image in between to separate them.

       There are some exception to this formula, however:
       - single-component illustrations, which can be generated with a single command.
       - duplicates of other illustrations, which can be generated by making a file copy of the original illustration.
       """

    # Offer an optional "write intermediate files" function, which would
    # be used to generate all of the component (e.g. -before.svg / -after.svg) files,
    # although I think it'd be better to name them something like `foo-before.svg.in`.
    #
    # The reason being that, by NOT naming the intermediates .svg, we can easily have
    # the Makefile compare the modification times of the .yaml files and the final .svg
    # files, and rebuild any that exhibit some changes.
    #
    # That might also be wise to check for the font files, but I'm less certain how to
    # implement that.
    
    def __init__(self, configfile=None):
        if configfile:
            with open(configfile, 'r') as file:
                config = yaml.safe_load(file)

                # Do safety checks before creating anything
                if config["SOLE_COMPONENT"] and config["components"]:
                    # Safety check; `SOLE_COMPONENTS` can't coexist with other formats
                    raise ValueError("Illustration cannot be a SOLE_COMPONENT and contain any other defined components")
                    
                self.name = config["name"]
                self.source = None

                # Optional fill color, defaults to black
                if config["basecolor"]:
                    self.basecolor = config["basecolor"]
                else:
                    self.basecolor = "000000"
            
                # Optional list of CSS color classes to assign
                # to <use> elements in output
                if config["cssclasses"]:
                    self.cssclasses = config["cssclasses"]
                else:
                    self.cssclasses = [] # ? or None?

                    
                # Optional "build intermediate files" option, from method arguments
                #if build_intermediates:
                self.build_intermediates = False
                    
                # Check if we need to build duplicate copies
                if config["duplicates"]:
                    #self.source = config["duplicates"].value # ? or just config["duplicates"]??
                    ## make_duplicate from value of "duplicates", name it "name"
                    ##
                    ## ... although that probably only NEEDS to be done at write() time
                    ##     ?
                    #self.layout = None
                    pass
                
                elif config["SOLE_COMPONENT"]:
                    #self.components = [self.name] # placeholding! we don't actually NEED a list of names
                    
                    # make a single svgComponent
                    # actually, maybe we need to instantiate it, then store .tree()?
                    self.components = [svgComponent(self.name,
                                                    config["GENERATOR"],
                                                    config["FONT"],
                                                    config["unicodes"],
                                                    config["margin"],
                                                    config["features"],
                                                    config["options"],     # add basecolor !!                                                
                                                    )]
                    self.layout = "solo"

                elif config["components"]:
                    # instantiate an svgComponent for each one; 
                    # we will need to handle 'file:' components separately here
                    for component in config["components"]:
                        if component["file"]:
                            self.components.append()
                        else:
                            self.components.append(svgComponent(component["name"],
                                                    component["GENERATOR"],
                                                    component["FONT"],
                                                    component["unicodes"],
                                                    component["margin"],
                                                    component["features"],
                                                    component["options"],     # add basecolor !!                                                
                                                    ))
                    self.layout = "horizontal"

                return None
            
        else:
            self.name = None
            self.components = []
            self.basecolor = "000000"
            self.source = None
            self.cssclasses = []
            self.duplicates = []
            self.build_intermediates = False
            self.layout = None

            return None

        
    def build(self):
        """Build the illustration, and populate self.data with the result.

        This method iterates through all of the consitutent svgComponents that
        make up the illustration, generating each (or loading it directly from
        an external file), then concatenates them into a single SVG.

        The resulting SVG representation is held in self.data as plain text (UTF-8).
        It is not exported to file; you must call .write() for that, after
        optionally updating the CSS classes of the constituent parts with
        .apply_css_classes().

        The .build() method *does* automatically set the viewBox to the correct
        width and height required to show all elements; this is necessary because
        some glyph-generating recipes produce outside of the original bounding
        box (e.g., mark positioning for non-spacing marks: the mark glyph may
        be set outside of the base glyph's bounding box, and the SVGs are generally
        set to the base glyphs' bounding boxes).
        """
        svgs = []
        self.data = None # do we need to initialize this in init?
                         # No; it's just going to be the text string of the SVG.
        print(f'Building {self.name}...', file=sys.stderr)
        if not self.components:
            raise ValueError("No components found.")
        else:
            print(f'[{self.name}]: Iterating through components...', file=sys.stderr)
            for component in self.components:
                #build the component
                svgs.append(component.generate())
                    
                if svgs:
                    if self.layout == "solo":
                        # no layout work is required
                        self.data = svgs[0]
                    elif self.layout == "horizontal":
                            
                        import svg_stack as ss
                        
                        doc = ss.Document()
                        layout1 = ss.HBoxLayout()
                            
                        for svg in svgs:
                            layout1.addSVG(svg, alignment=ss.AlignCenter)
                                
                            doc.setLayout(layout1)
                                
                            self.data = doc.save() # ????? ?????
                            # Seems like we need to save this to an instance attribute,
                            # but ss.doc only saves to a "fileobj"
                            #
                            # early research says contextlib can perhaps capture this?
                            #
                            # ...anyway, maybe self.contents ...
                            #       then we can assign cssclasses and do the viewbox
                            #       then, on .write(), we would do the ID attributes, because
                            #       that might involve generating duplicates
                                
                    else:
                        raise NotImplementedError("Unknown composite layout requested. Only 'solo' and 'horizontal' are supported.")
                            
                else:
                    raise ValueError("No SVG elements found.")

                
        # apply viewbox to self.data
        print(f'[{self.name}]: Applying viewbox to the illustration.', file=sys.stderr)
        if not self.data:
            raise ValueError("No SVG elements found.")
        else:
            # Ugly, but works for the moment. All SVGs from hb-view and svg_stack use this namespace string....
            namespace = "{http://www.w3.org/2000/svg}"
            tree = ET.parse(self.data)
            root = tree.getroot()

            # This nsmap stuff can probably be removed; we could then remove lxml
            # from the build requirements....
            d = root.nsmap
            #print(d)
            #del d[None]
            #d["svg"] = namespace[1:-1]
            #print(d)
            #print(root.tag)

            # Check whether or not this is an SVG tree that we know how to work with
            if (root.tag != namespace + "svg"):
                print(f'[{self.name}]: Parsing trouble; it\'s unclear if this is a compatible SVG', file=sys.stderr))
                raise ValueError(f'Root element: {root.tag}')
            else:
                if ("width" in root.attrib) and ("height" in root.attrib):
                    # copy the width and height into a new viewBox
                    # assign "100%" as the new width and remove the height attribute
                    if ("viewBox" in root.attrib):
                        print(f'[{self.name}]: Unexpected: perhaps this SVG already has a viewBox?', file=sys.stderr)))
                        raise ValueError("viewBox is; ", root.attrib["viewBox"])
                    else:
                        w = root.attrib["width"]
                        h = root.attrib["height"]
                        root.attrib["viewBox"] = "0 0 " + w + " " + h
                        root.attrib["width"] = "100%"
                        root.attrib.pop("height")

                        # Paste the updated tree back to self.data ... as a string, since it was before ??
                        self.data = ET.tostring(tree, encoding="unicode")
                else:
                    print(f'[{self.name}]: Unexpected: this SVG is missing width or height attributes?', file=sys.stderr))
                    raise ValueError(f'Width: {root.attrib["width"]}, Height: {root.attrib["height"]}')
            
        
        # apply cssclasses to self.data
        # ...maybe we should make that a feature that needs to be called explicitly, so we can test
        # the SVG component generation, etc, regardless of whether we know (or even have) CSS classes/colors
        return None

    
    # Can / should this be an instance property?
    #
    # I don't know why I'd need a getter... maybe to extract them for the YAML?
    #
    # I think making this a function will make it easier
    # to skip this step for PDF (or other noninteractive)
    # output formats.
    def apply_css_classes(self, classlist=self.cssclasses):
        """Assign the provided CSS classes to the <use> elements in the illustration.

        This method updates the SVG data in self.data, by assigning a CSS class from
        `classlist`, in the order found, to the <use> elements in the SVG.

        As of now, all SVG images generated by hb-view and svg_stack are structured so
        that the top-level shapes are rendered into the viewport through a <use> element.
        Consequently, CSS and JavaScript can only affect the appearance of the shapes
        through these <use>s.
        """
        # Change of thought; we don't start out with any classes at all, so we don't need to check
        # for the presence of all of the possibilities. Perhaps we'll need to for some future SVG
        # component generator, but for now we can just add the ones requested in self.cssclasses.
        #if any (x in classlist for x in e.classes):
        #    raise ValueError(f'[{self.name}]: Unexpected: an element already includes an illustration CSS class')
        
        print(f'[{self.name}]: Applying CSS classes to the <use> elements in the illustration.', file=sys.stderr)
        
        if not self.data:
            raise ValueError(f'[{self.name}]: The illustration does not contain SVGs in its .data attribute;
            it must be built before CSS classes can be assigned.')
        else:
            # Check the length of the classlist?
            u_count = self.data.count("<use ")
            c_count = len(classlist)
            if u_count != c_count:
                raise ValueError(f'[{self.name}]: Mismatched counts. Found {u_count} <use> elements but {c_count} CSS classes were provided.')
            else:
                # Ugly, but works for the moment. All SVGs from hb-view and svg_stack use this namespace string....
                namespace = "{http://www.w3.org/2000/svg}"
                tree = ET.parse(self.data)
                root = tree.getroot()

                # This nsmap stuff can probably be removed; we could then remove lxml
                # from the build requirements....
                d = root.nsmap
                #print(d)
                #del d[None]
                #d["svg"] = namespace[1:-1]
                #print(d)
                #print(root.tag)

                # Check whether or not this is an SVG tree that we know how to work with
                if (root.tag != namespace + "svg"):
                    print(f'[{self.name}]: Parsing trouble; it\'s unclear if this is a compatible SVG', file=sys.stderr)
                    raise ValueError(f'Root element: {root.tag}')
                else:
                    # iterate through the entire tree
                    elems = list(root.iter())
                    for elem in elems:
                        # inserting a generic 'class=""' into each <use> element
                        if (elem.tag == namespace + "use"):
                            if ("class" not in elem.attrib):
                                # TODO: support a user-supplied class attribute, either directly
                                #       or via a class list for the whole file, which we
                                #       would then store in the docs.
                                # TODO: append to the class, rather than replacing it.
                                #       Not sure how duplicate classes would be handled by ETree....
                                elem.attrib["class"] = classlist.pop(0)
                                print(elem.tag, elem.attrib["class"])
                            else:
                                # We should pass pre-existing class attributes through, not considering them errors
                                print(f'[{self.name}]: Unexpected: encountered a <use> element with non-empty classes', file=sys.stderr)
                                raise NotImplementedError(f'{elem.tag} has CSS classes: {elem.attrib["class"]}')

                    # Paste the updated tree back to self.data ... as a string, since it was before ??
                    self.data = ET.tostring(tree, encoding="unicode")
                
        return None

    
    def prepend_elementIDs(svg_data, id_prefix):
        """Insert a prefix into the ID of  each SVG element, to ensure uniqueness.

        This function is meant to guarantee that every SVG and all of that SVGs child
        elements has an ID attribute that is unique within the entire document. The
        uniqueness is mandatory because the SVG images are inlined into the HTML file
        output: any elements that share a non-unique ID would all be affected by CSS
        and JavaScript simultaneously, because all inline SVG elements belong to the
        single, shared namespace/DOM of the HTML page.

        The inlining itself is mandatory because CSS and JavaScript cannot modify SVG
        objects that are included on the HTML page as external <img src="foo"> elements.
        Or, at least, not reliably, and not with most browsers.
        """
        print(f'[{self.name}]: Inserting prefixes to the ID attributes of all elements in the illustration.', file=sys.stderr)

        if not svg_data:
            raise ValueError(f'[{self.name}]: The illustration does not contain SVGs in its .data attribute;
            it must be built before CSS classes can be assigned.')
        if not id_prefix:
            raise ValueError('No ID prefix was supplied.')
        
        # Ugly, but works for the moment. All SVGs from hb-view and svg_stack use this namespace string....
        namespace = "{http://www.w3.org/2000/svg}"
        tree = ET.parse(self.data)
        root = tree.getroot()

        # This nsmap stuff can probably be removed; we could then remove lxml
        # from the build requirements....
        d = root.nsmap
        #print(d)
        #del d[None]
        #d["svg"] = namespace[1:-1]
        #print(d)
        #print(root.tag)

        # Check whether or not this is an SVG tree that we know how to work with
        if (root.tag != namespace + "svg"):
            print(f'[{self.name}]: Parsing trouble; it\'s unclear if this is a compatible SVG', file=sys.stderr)
            raise ValueError(f'Root element: {root.tag}')
        else:
            if ("id" not in root.attrib):
                # insert id_prefix as the id for the complete SVG
                #print(f'[{self.name}]: no pre-existing #id', file=sys.stderr)
                root.attrib["id"] = id_prefix
            else:
                # Need to make these actual exceptions
                print(f'[{self.name}]: Unexpected: this SVG root element already has an id!', file=sys.stderr)
                raise ValueError(f'Root id is: {root.attrib["id"]}')
                
            # iterate through the entire tree
            elems = list(root.iter())
            for elem in elems:
                # ... prepending id_prefix to all id declarations
                if (elem != root and "id" in elem.attrib):
                    print(f'[{self.name}]: {elem.tag} id = {elem.attrib["id"]}', file=sys.stderr)
                    old_id = elem.attrib["id"]
                    if old_id[0:1] != "id":
                        elem.set("id", id_prefix + ":" + old_id)
                        print(f'[{self.name}]: Element {elem.tag}, assigning id: {elem.attrib["id"]}', file=sys.stderr)
                    else:
                        print(f'[{self.name}]: Error: {elem.tag} has unexpected id: {elem.attrib["id"]}', file=sys.stderr)
                        raise ValueError(f'Element id found = {elem.attrib["id"]}')
                    
                # ... prepending id_prefix to all id hrefs
                if ( "{" + d["xlink"] + "}" + "href" in elem.attrib):
                    print(f'[{self.name}]: Found xlink element', file=sys.stderr)
                    old_target = elem.attrib["{" + d["xlink"] + "}" + "href"]
                    # TODO: test whether the following syntax (which is used to access the xlink href)
                    #       also gets written out correctly to the file.

                    if old_target[1:2] != "id":
                        elem.set("{" + d["xlink"] + "}" + "href", "#" + id_prefix + ":" + old_target[1:])
                        print(elem.attrib, file=sys.stderr)
                    else:
                        print("Error: ", elem.tag, " has unexpected target: ", old_target, file=sys.stderr)

        # Return the altered SVG as a string, since it's intended to be written to file
        return ET.tostring(tree, encoding="unicode")


    
    def write(self, filename_stub=self.name):
        """Write the illustration to an SVG file, using the supplied filename stub.

        This will also write out any requested duplicate illustrations into their own
        SVG files, using the filename stubs found in the `duplicates` block in the
        YAML configuration file for the primary illustration."""
        print(f'[{self.name}]: Writing SVG content out to files', file=sys.stderr)
        
        if not self.data:
            raise ValueError(f'[{self.name}]: Writing to file: the illustration does not contain SVGs in its .data attribute;
            it must be built before it can be written out to file.')
        if not filename_stub:
            raise ValueError(f'[{self.name}]: Writing to file: No output filename pattern was supplied.')

        # Regardless of whether there are or are not any duplicates (as tested below), 
        # apply element IDs to self.data, using the unaltered name, then write that out
        # to file.
        # Here, as elsewhere, we probably don't need to update self.data. Doing so might
        # save a few cycles if we were writing again and again, but that's not the use case.
        with open(filename_stub + ".svg", w+t, encoding="utf-8") as outfile:
            print(f'[{self.name}]: Writing SVG content out to file {filename_stub}.svg', file=sys.stderr)
            outfile.write( prepend_elementIDs(self.data, filename_stub) )

        # Handle all requested image duplicates.
        if self.duplicates:
            # We need to create a copy for each entry in the self.duplicates list
            #exec("cp ", self.duplicate, filename_stub + ".svg") # use Pathlib !!
            for duplicate in self.duplicates:                
                # apply element IDs to self.data, using 'duplicate' instead of filename_stub
                # ... so, make an ET.tree for each duplicate, apply the ID, write it to
                # its own file, but don't overwrite that ET.tree back into self.data
                with open(duplicate + ".svg", w+t, encoding="utf-8") as outfile:
                    print(f'[{self.name}]: Writing SVG content out to duplicate illustration {duplicate}.svg', file=sys.stderr)
                    outfile.write( prepend_elementIDs(self.data, duplicate) )
                    
        return None
    

    # Can / should this be an instance property?
    #
    # I don't know why I'd need a getter... maybe to extract them for file writing
    def set_name(self, new_name):
        """Insert the provided new_name as the prefix token
           for all necessary elements."""
        # I think making this a function will make it easier
        # to generate duplicates when necessary
        self.name = new_name
        return None

        


def extract_color_classes(filename):
    """Extracts an ordered list of the color classes in an SVG file."""
    from lxml import etree as ET
#
    namespace = "{http://www.w3.org/2000/svg}"
#        
    with open(filename, 'r+t', encoding='utf-8') as svg:
        tree = ET.parse(svg)
        root = tree.getroot()
#
        d = root.nsmap
        if (root.tag != namespace + "svg"):
            raise Exception("Parsing trouble; it's unclear if the SVG file is compatible.")
        else:
            cssclasses = []
            elems =  list(root.iter())
            for elem in elems:
                if (elem.tag == namespace + "use"):
                    if "class" in elem.attrib:
                        cssclasses.append(elem.attrib["class"])
                    else:
                        print(f'Warning: found <use> element with no classes: {elem}', file=sys.stderr)
#
    return cssclasses


def _insert_ids(svgstring, id_token):
    #id_token = Path(svgstring).stem
    
    # Ugly, but works for the moment
    namespace = "{http://www.w3.org/2000/svg}"

    #tree = ET.fromstring(bytes(svgstring.text, encoding='utf-8'))
    #root = tree.getroot()
    #root = ET.fromstring(bytes(svgstring, encoding='utf-8'))
    root = ET.fromstring(svgstring)

    # This nsmap stuff can probably be removed; we could then remove lxml
    # from the build requirements....
    d = root.nsmap

    # Check whether or not this is an SVG tree we know how to work with
    if (root.tag != namespace + "svg"):
        # need to make these actual exceptions
        print("Parsing trouble; it's unclear if this is a compatible SVG", file=sys.stderr)
        print(f'Root element: {root.tag}')
        return None
    else:
        if ("id" in root.attrib):
            # Need to make these actual exceptions
            print("Error: this root element already has an id!", file=sys.stderr)
            print(f'Root id is: {root.attrib["id"]}', file=sys.stderr)
            return None
        else:
            # insert id_token as the id for the svg
            print("Good: no pre-existing #id", file=sys.stderr)
            root.attrib["id"] = id_token

            # iterate through the entire tree
            elems = list(root.iter())
            for elem in elems:
                    
                # ... prepending id_token to all id declarations
                if (elem != root and "id" in elem.attrib):
                    print(f'Adding id to {elem.tag}: {elem.attrib["id"]}', file=sys.stderr)
                    old_id = elem.attrib["id"]
                    if old_id[0:1] != "id":
                        elem.set("id", id_token + ":" + old_id)
                        print(elem.tag, elem.attrib["id"], file=sys.stderr)
                    else:
                        print(f'Warning: {elem.tag} has unexpected id {elem.attrib["id"]}', file=sys.stderr)
                        
                # ... prepending id_token to all id hrefs
                if ( "{" + d["xlink"] + "}" + "href" in elem.attrib):
                    print("Found xlink", file=sys.stderr)
                    old_target = elem.attrib["{" + d["xlink"] + "}" + "href"]
                    # TODO: test whether the following syntax (which
                    # is used to access the xlink href) also gets
                    # written out correctly to the file.

                    if old_target[1:2] != "id":
                        elem.set("{" + d["xlink"] + "}" + "href", "#" + id_token + ":" + old_target[1:])
                        print(elem.attrib, file=sys.stderr)
                    else:
                        print(f'Error: {elem.tag} has unexpected target {old_target}', file=sys.stderr)

        return ET.tostring(root)

    
def _insert_viewbox(svgstring):
    #id_token = Path(svgfile).stem
    
    # Ugly, but works for the moment
    namespace = "{http://www.w3.org/2000/svg}"

    #tree = ET.fromstring(bytes(svgstring, encoding='utf-8'))
    # apparently, .fromstring() returns the root itself, rather than
    # the tree, just to be different....
    #tree = ET.parse(bytes(svgstring, encoding='utf-8'))
    #tree = ET.parse(svgstring)
    #print(tree.tostring())
    # ... AND it also has no .tostring() method, because why create
    # interfaces that people would use???

    #root = tree.getroot()
    root = ET.fromstring(bytes(svgstring, encoding='utf-8'))
    #root = ET.fromstring(svgstring)
    #print(ET.tostring(root))
    
    # This nsmap stuff can probably be removed; we could then remove lxml
    # from the build requirements....
    #d = root.nsmap

    if ("width" in root.attrib) and ("height" in root.attrib):
        # copy the width and height into a new viewBox
        # assign "100%" as the new width and remove the height attribute
        if ("viewBox" in root.attrib):
            print("Warning: this SVG already has a viewBox?", file=sys.stderr)
            print(f'viewBox is: {root.attrib["viewBox"]}', file=sys.stderr)
            return ET.tostring(root)
        else:
            w = root.attrib["width"]
            h = root.attrib["height"]
            root.attrib["viewBox"] = "0 0 " + w + " " + h
            root.attrib["width"] = "100%"
            root.attrib.pop("height")

            return ET.tostring(root)
        
    else:
        print("Warning: this SVG is missing width or height attributes", file=sys.stderr)
        print(f'Width: {root.attrib["width"]}, Height: {root.attrib["height"]}', file=sys.stderr)
        return None




def sample_page(dirname):
    """Returns a before-and-after sample page comparing all SVG illustration
       pairs in the given directory. Any standalone SVG files are also
       rendered, in their own section."""
    import os
    import pathlib
    from lxml import etree as ET

    
    dir_short = os.path.basename(os.path.normpath(dirname)) # Keepin' the HTML tidy
    htmlpage = (
        f'<html>\n'
        f'<head>\n<title>SVG samples from {dir_short}</title>\n</head>\n'
        f'<body>\n'
        f'<h1>SVGs found in {dirname}</h1>\n<br>\n'
        f'<h2>Before-and-after pairs:</h2>\n'
        f'<table>\n<thead>\n<tr><th>Before</th><th>After</th></tr>\n</thead>\n'
        f'<tbody>\n'
        )

    svgs = list(pathlib.Path(dirname).glob('*.svg'))

    #svgs = list(pathlib.Path(dirname, pathlib.Path(dirname).glob('*.svg') ))
    #svgs2 = [pathlib.Path(dirname, s) for s in svgs]
    #print(svgs2)
    befores = sorted([s for s in svgs if "-before" in str(s)])
    afters = sorted([s for s in svgs if "-after" in str(s)])
    stubs = [str(s).rpartition("-before.svg")[0] for s in befores]
    #print(svgs)

    #
    # This pair-finding method fails if any of the expected component
    # SVG files is missing. It might also fail on `right-arrow.svg` in
    # the case where there are filenames alphabetically after it.
    svg_pairs = [ [b, a] for b,a in zip(befores, afters) if str(b).rpartition("-before.svg")[0] == str(a).rpartition("-after.svg")[0]]

    if len(svg_pairs) > 0:
        for pair in svg_pairs:
            print(f'pair: {pair}', file=sys.stderr)
            # update with _insert_ids() and _insert_viewbox() steps here
            # on pair[0] and pair[1]
            #
            # The immutability of the string variables here is why we need
            # to replace that with a svgComponent class that has a tree
            # representation attribute....
            #with open(pair[0], 'r+t', encoding='utf-8') as b, open(pair[1], 'r+t', encoding='utf-8') as a:
            b = Path(pair[0]).read_text()
            print(f'b:: {b}', file=sys.stderr) # debugging: somehow this isn't becoming a string?
            a = Path(pair[1]).read_text()
            bv = _insert_viewbox(b)
            av = _insert_viewbox(a)
            bi = _insert_ids(bv, str(os.path.basename(pair[0])))
            ai = _insert_ids(av, str(os.path.basename(pair[1])))
            
            htmlpage += (
                f'<tr><td>{str(os.path.basename(pair[0]))}<br>'
                #f'<img src="{pair[0]}">' # when we are inlining the SVGs, we'll replace the <img> element here
                f'{bi.decode('utf-8')}'
                f'</td><td>{str(os.path.basename(pair[1]))}<br>'
                #f'<img src="{pair[1]}">' # when we are inlining the SVGs, we'll replace the <img> element here
                f'{ai.decode('utf-8')}'
                f'</td></tr>\n'
            )
            svgs.remove(pair[0])
            svgs.remove(pair[1])
        
    htmlpage += (
        f'</tbody>\n'
        f'</table>\n'
        )

    if len(svgs) > 0:
        htmlpage += (
            f'<br>\n'
            f'<h2>Unpaired SVGs:</h2>\n'
            f'<table>\n<thead>\n<tr><th>Image</th></tr>\n</thead>\n'
            f'<tbody>\n'
        )

        for svg in svgs:
        # update with _insert_ids() and _insert_viewbox() steps here
            s = Path(svg).read_text()
            print(f"s:: {s}", file=sys.stderr)
            svgv = _insert_viewbox(s)
            svgi = _insert_ids(svgv, str(os.path.basename(svg)))
            htmlpage += (
                #f'<tr><td>{str(os.path.basename(svg))}<br><img src="{svg}"></td></tr>\n' #when we are inlining the SVGs, we'll replace the <img> element here
                f'<tr><td>{str(os.path.basename(svg))}<br>{svgi.decode('utf-8')}</td></tr>\n'
            )

        htmlpage += (
            f'</tbody>\n'
            f'</table>\n'
        )
        
    htmlpage += (
        f'</tbody>\n'
        f'</body>\n'
        f'</html>'
        )
    
    return htmlpage
    #print([str(s) for s in svgs])
    #print(befores)
    #print(afters)
    #print(stubs)
    #print(svg_pairs)
    #print(htmlpage)
    #print(svgs)
    #return None

def _bootstrap_colorclasslist(filename):
    """Inserts YAML configuration for SVG images, capturing the CSS
       color classes applied to each <use> element, in order.

       This is a bootstrapping function used solely to migrate the old,
       'SCRIPT-svg-generation-log.md' files to YAML configuration.

       Some of the log files already contain the necessary information.
       In those cases, it is written as-is into the .yaml configuration
       files on a per-image basis. For the other log files, the function
       bootstraps that information by extracting it from the current
       .svg files.

       Consequently, this function remains private, because in the long
       term, the build tool cannot rely on the "current as of now" files
       containing the necessary color classes.
    """

    return None

    
def _bootstrap_duplicates_to_line(filename):
    """Inserts YAML configuration for SVG images that are duplicates
       of another illustration.

       This is a bootstrapping function used solely to migrate the old,
       'SCRIPT-svg-generation-log.md' files to YAML configuration.

       This version inserts references to duplicates as a `duplicate`
       line within the YAML file for each original file.

       It is NOT clear at the time of writing whether or not such a
       configuration is ideal.

       For the alternative approach, see _bootstrap_duplicates_to_file().

       Args:
           filename: an svg-image-generation-log.md file containing the
             hb-view and svg_stack.py commands used to build the images
             in the current directory. This function only acts on `cp`
             commands found within the file. It has no function otherwise.
    
       Returns:
           None
    
       Appends:
           Adds lines to the end of set of *.yaml files, each of which
           is named for the script-feature combination that original
           SVG image should illustrate. This function adds a `duplicates`
           block, where needed, indicating that the image builder must
           make copies of the configured image (with the supplied list
           noting what the copies need to be named, and implicitly how
           many of them there will be."""
    from collections import defaultdict
    
    output_files = defaultdict(list)
    
    with open(filename, 'r+t', encoding='utf-8') as log:
        lines = log.readlines()
        for line in lines:
            
            params = {}
            if line[:2] == "cp":
                print(line, file=sys.stderr)
                # Hmm. We don't have params yet....
                #   ** fixed; the declaration up & out of the with() block
                p = line[2:].split()
                params["target"] = p[0][:-4]
                params["duplicate"] = p[1][:-4]

                # create a YAML `duplicate` element and add it
                # to the output_files collection
                #
                yaml_duplicate = (
                    f'- {params["duplicate"]}\n'
                )

                output_files[params["target"]].append(yaml_duplicate)

    # Iterate through all the output files,
    # 1. open the EXISTING "target" file in "append" mode
    # 2. Start a "duplicates" block
    # 3. Iterate through all the duplicates, adding each on its own line
    for target, duplicate_list in output_files.items():
            with open(target + ".yaml", 'a', encoding='utf-8') as outfile:
                print(f'Appending to {target}.yaml', file=sys.stderr)
                yaml_out = (
                    f'duplicates:\n'
                )
                
                for duplicate in duplicate_list:
                    yaml_out += duplicate

                # Write to file
                outfile.write(yaml_out)

    return None
    
    
def _bootstrap_duplicates_to_file(filename):
    """Generates YAML configuration for SVG images that are duplicates
       of another illustration.

       This is a bootstrapping function used solely to migrate the old,
       'SCRIPT-svg-generation-log.md' files to YAML configuration.

       This version creates a standalone YAML file for each duplicate
       image, with that YAML file containing a reference to the original
       file.

       It is NOT clear at the time of writing whether or not such a
       configuration is ideal.

       For the alternative approach, see _bootstrap_duplicates_to_line().

       Args:
           filename: an svg-image-generation-log.md file containing the
             hb-view and svg_stack.py commands used to build the images
             in the current directory. This function only acts on `cp`
             commands found within the file. It has no function otherwise.
    
       Returns:
           None
    
       Writes:
           A set of *.yaml files, each of which is named for the output filename
           of the duplicate SVG file that should be generated (with the .yaml
           extension replacing the .svg extension to be used in the final image),
           and each of which contains a one-line "duplicates: foo" line that
           designates the name of the original file that will be duplicated to
           result in the final image file."""

    base_dir = Path(filename).parents[0]
    
    with open(filename, 'r+t', encoding='utf-8') as log:
        lines = log.readlines()
        for line in lines:
            
            if line[:2] == "cp":
                print(f'File {filename}, line: {line}', file=sys.stderr)
                # Hmm. We don't have params yet....
                #   ** fixed; the declaration up & out of the with() block
                p = line[2:].split()
                target = p[0][:-4]
                duplicate = p[1][:-4]

                with open(Path(base_dir, duplicate + ".yaml"), 'w+t', encoding='utf-8') as outfile:
                    print(f'Writing {duplicate}.yaml', file=sys.stderr)
                    yaml_out = (
                        f'name: {duplicate}\n'
                        f'duplicates: {target}\n'
                        )

                    #print(yaml_out, file=sys.stderr) # Here we'd actually write the file
                    outfile.write(yaml_out)

    return None
    
    
def _bootstrap_yaml(filename):
    """Builds a YAML configuration file from an SVG generation log entry.

       This is a bootstrapping function used solely to migrate the old,
       'SCRIPT-svg-generation-log.md' files to YAML configuration.

       Args:
           filename: an svg-image-generation-log.md file containing the
             hb-view and svg_stack.py commands used to build the images
             in the current directory.
    
       Returns:
           None
    
       Writes:
           A set of *.yaml files, each named for the script-feature
           combination that the SVG image should illustrate."""

    from collections import defaultdict

    base_dir = Path(filename).parents[0]

    # Let's just collect the results as raw YAML, then sort them out later.
    output_files = defaultdict(list)

    # Might be more useful to pass in values as function parameters?
    arrow_font = ""
    script_font = ""
    params = {}
    
    with open(filename, 'r+t', encoding='utf-8') as log:
        lines = log.readlines()
        for line in lines:
            # Capture any existing filepath definitions...
            # - This won't be necessary in general, but some existing
            #   svg-generation-logs have already been touched.
            if line[:10] == "ARROWFONT=":
                arrow_font = line[10:]
            elif line[:11] == "SCRIPTFONT=":
                script_font = line[11:-1] # :-1 cuts off the newline

            # Handle hb-view lines...
            # - Each line can only represent one component.
            elif line[:8] == "hb-view ":
                # Start a new YAML 'component'...
                #
                # Convert command arguments into a dictionary.
                #
                # This doesn't work; the font parameter doesn't use '='
                #params = {k: v for k, v in map(lambda x: x.replace("$").replace()..split("="), cmd)}
                #params = [i for i in cmd if "=" in i]
                
                #params = {}
                for param in line[8:].split():
                    if "=" not in param:
                        if param[:2] == "--": # extra flags !
                            params["options"] += param # actually, there could be more than one of these....
                        else:
                            params["font"] = param
                    else:
                        p = param.split("=")
                        params[p[0][2:]] = p[1]
                #print(params) # debugging
                

                # Get the component name from 'output-file'...
                #
                if params["output-file"] == "right-arrow.svg":
                    # It's the right-arrow command, which is
                    # a special case we only need to generate
                    # once in the entire directory.
                    #params["target"] = "arrow" # The 'target' is not part of the right-arrow generation command.
                    yaml_component = (
                        f'- arrow:\n'
                        f'  - file: right-arrow.svg'
                        )
                else:
                    # This actually fails for the right-arrow SVG.
                    # But we actually only need that once. So we
                    # shouldn't re-generate it for every illustration
                    # anyway....
                    # [x] :. special-case 'right-arrow.svg'
                    #
                    # Actually, this also fails for the single-component
                    # images, too. E.g., khmer-robat.svg, tibetan-syllable.svg
                    # [ ] - :. add test for how many "-" there are?
                    #filename_parts = params["output-file"].rpartition("-")
                    filename_parts = params["output-file"].split("-")
                    #print(filename_parts) # Debug
                    if len(filename_parts) < 3:
                        params["target"] = params["output-file"][:-4]
                        #params["name"] = params["output-file"][:-4]
                                         # probably a different component-name is needed
                        params["name"] = "SOLE_COMPONENT" # special case in builder
                    else:
                        params["target"] = params["output-file"].rpartition("-")[0]
                        params["name"] = params["output-file"].rpartition("-")[2][:-4]

                    # `unicodes` is required; other parameters have defaults...
                    # - Pass through unicodes as-is...
                    # - Pass through margin as-is...
                    # - Pass through features as-is...

                    # The font is also required, but may be set already...
                    # Get font if it's not SCRIPTFONT...

                    yaml_component = (
                        f'- {params["name"]}:\n'
                        f'    unicodes: {params["unicodes"]}\n'
                        )

                    if params["font"] != "$SCRIPTFONT":
                        yaml_component += (
                            f'    font: {params["font"]}\n'
                            )

                    if params["margin"]:
                        yaml_component += (
                            f'    margin: {params["margin"]}\n'
                            )

                    if params["features"]:
                        yaml_component += (
                            f'    features: {params["features"]}\n'
                            )

                    # Add this component block to the collection for output
                    output_files[params["target"]].append(yaml_component)

                # Debugging to console output, because special cases happen....
                if params["font"] != "$SCRIPTFONT":
                    # This image needs a non-standard example font:
                    print(f"Warning, non-standard font {params}", file=sys.stderr)
                    
            # The `line` processing is complete.
        
        # Processing all the lines is complete.
        
        # Iterate through the data, starting a new YAML file for each
        # `target`...
        for target, component_list in output_files.items():
            with open(Path(base_dir, target + ".yaml"), 'w', encoding='utf-8') as outfile:
                # This overwrites the file entirely, which is OK because
                # we're just bootstrapping the old repo into the new format.
                print(f'Writing {outfile}', file=sys.stderr)
                yaml_out = (
                    f'name: {target}\n'
                    f'GENERATOR: hb-view\n'
                    f'FONT: {script_font}\n' # stray \n sneaks in here?
                    f'basecolor: 000000\n'
                    f'components:\n'
                )
                # Add each of the collected components in its own block...
                #
                # Actually, we need to do this in a specific
                # order: -before, -arrow, -after....
                #
                # Or else have the builder Just Know that order....
                #
                # That's probably fine, since the order in the un-converted
                # -log.md files is predictably correct.
                for component in component_list:
                    yaml_out += component

                # TODO (maybe?):
                #
                # handle CSS color-codes?
                # 1. must be run on 'target' final filename
                # 2. must be run AFTER all components.
                # 3. :. must be done outside _build_yaml() or at least
                #    outside this loop.
                #   3.1. have _build_yaml() return yaml string,
                #   3.2. make a _write_yaml() that takes yaml string input
                # 4. some existing files have cluster_styles lines already
                #
                # insert a right-arrow block?
                # 1. It's probably the same for every SVG illustration
                #    in the directory
                # 2. But we can't fully assume that every image needs it
                #    or places it in the correct order. There are some
                #    examples like alternate forms that JUST show some
                #    glyphs in sequence, with no arrow....
                # 3. Bigger question is whether to use a different YAML
                #    config file (and reference it) for each arrow use,
                #    or to generate every one.

                # Write to file
                outfile.write(yaml_out)

                
        if not arrow_font:
            print("Uh-oh; no arrow font.", file=sys.stderr)
            arrow_font = ""

    return None


if __name__ == '__main__':   # Really needs argparse....
    from pathlib import Path
    #extract_color_classes(sys.argv[1])
    _bootstrap_yaml(sys.argv[1])
    #_bootstrap_duplicates_to_line(sys.argv[1])
    _bootstrap_duplicates_to_file(sys.argv[1])
    #
    # test sample-page generator
    #with open(sys.argv[2], 'w', encoding='utf-8') as outfile:
    #    outfile.write(sample_page(sys.argv[1]))
    #
    # test _insert* functions
    #with open(sys.argv[1], 'r+t', encoding="utf-8") as svgfile:
    #    temporary_string = svgfile.read()
    # test viewbox inserter
    #print(_insert_viewbox(temporary_string))
    # test id inserter
    #filestem = Path(sys.argv[1]).stem
    #print(_insert_ids(temporary_string, filestem))
    
