#!/usr/bin/python3
# SPDX-FileCopyrightText: Copyright 2026 Nathan Willis
#
# SPDX-License-Identifier: BSD-2-Clause
"""SVG illustration-building system for the opentype-shaping-documents repository.
"""

import sys
import yaml
from lxml import etree as ET
from pathlib import Path

import vharfbuzz as vh

#
# Constants
#

CSS_CLASSLIST = ["c0", "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "dc", "arrow"]
"""A list of the known CSS classes applied for SVG illustration interactivity."""

FONTDIR = "images/example-fonts/"
"""The directory where the binary font files indicated in various illustration YAML configuration
   files are to be found.

   The location must be relative to the document root of the Git repository. The document root of
   the Git repository is expected to also be root directory of the Sphinx document-build system.

   This directory-location variable is included purely as a convenience to shorten the individual
   file paths within the YAML configuration files, by referencing `$FONTDIR`. Individual font
   files can be specified in other filesystem locations by omitting the reference to FONTDIR and
   pointing to other files."""

# Margin value of hb-view is in points (1/72 in)
# https://github.com/harfbuzz/harfbuzz/issues/1186#issuecomment-424780696
#
# CSS pixels are 1/96 in
# https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/length#absolute_length_units
#
# :. (72 / 96)pt = 1px
# pix_margin = pt_margin * (96/72)
def hb_pt_to_px(points):
    """Convert lengths in points to the equivalent in pixels."""
    return points * (72 / 96)


def hb_px_to_pt(pixels):
    """Convert lengths in pixels to the equivalent in points."""
    return pixels * (96 / 72)


class svgComponent():
    """An individual SVG component within a full illustration.

    Here, "individual component" essentially means a image that can be
    generated by a single command. The full illustration typically consists
    of several individual components that cannot be built all at once
    because they require different feature settings, margins, or perhaps
    different source fonts.

    See also svgFileComponent, which represents the simpler case of an
    individual component that can be read from an external file and does
    not require generation.
    """
    def __init__(self,
                 name,
                 fontfile,
                 unicodes,
                 fontsize,
                 margin,
                 features=None,
                 options=None,
                 generator="hb-view",
                 basecolor="000000",
                 ):

        from pathlib import Path

        self.name = name 
        self.tree = None # May not be needed; initializing to None just so that the attribute is always there upstream
        self.root = None # Also may not be needed; root is gettable from tree

        # turn `fontfile` into an absolute path
        print(f'[Component `{self.name}`]: fontfile reference = {fontfile}', file=sys.stderr)
        p = Path(fontfile)
        if p.is_absolute():
            self.font = p
            print(f'fontfile path: {p} ... cwd: {Path.cwd()} ... absolute: {p.resolve()}')
        elif p.exists():
            if DOCROOT:
                # compose new path as DOCROOT + fontfile
                p = Path(DOCROOT, p)
                p.resolve()
                self.font = p
        else:
            raise OSError(f'[Component `{self.name}`]: the font file {fontfile} could not be located. Does {p} exist?')
        
        self.unicodes = unicodes
        self.fontsize = fontsize
        self.margin = margin
        self.features = features
        self.options = options 
        self.generator = generator
        self.basecolor = basecolor
         
        return None


    def generate(self):
        """Generate a fresh instance of the SVG component from its configuration.

         This calls out to the system to execute `self.generator`, so if the configred
         generator program is not found, the generation will fail. A simple test is
         currently used that is expected to behave reasonably on Linux and Linuxy OSes.

         At present, the only generator supported in `hb-view`. Support for any new
         generators should be added here (or, at least, started here).
         """
        #import sys # not needed; should be loaded from package
        import shutil
        import subprocess

        # test that self.generator exists
        print(f'[Component `{self.name}`]: Checking for the presence of image generator: {self.generator}', file=sys.stderr)
        if not shutil.which(self.generator):
            raise Exception(f'[Component `{self.name}`]: The image generator {self.generator} cannot be found on the system.')
        else:
            print(f'[Component `{self.name}`]: image generator {self.generator} exists', file=sys.stderr)
            # build the command
            command = [f'{self.generator}',
                       "--output-format=svg",            # generates SVG output, and sends it to stdout
                       f'--font-size={self.fontsize}',
                       f'--margin={self.margin}',
                       f'--features={self.features}',
                       f'--foreground={self.basecolor}',
                       f'--background=FFFFFF00',         # for now, make this transparent
                       f'{self.font}',                   # for hb-view, this must come next-to-last
                       f'--unicodes={self.unicodes}',    # for hb-view, this must come last
                       ]

            # call the command, capturing the results from stdout
            print(f'[Component `{self.name}`], generate command: {command}', file=sys.stderr)
            result = subprocess.run(command, capture_output=True, encoding="utf8")
            print(f'[Component `{self.name}`] generated', file=sys.stderr)
            #result = subprocess.run(command, stdout=subprocess.PIPE)
            if result.returncode:
                print(f'[Component `{self.name}`]: image generator error: return code {result.returncode}')
                raise OSError(f'[Component `{self.name}`]: {result.stderr}')

        # capture any errors and raise them as exceptions from stderr?
        return result.stdout


    # TODO: for writing out to an intermediate file, which may be a useful debugging aid
    #
    #    This is speculative. We can already just dump an 'svg' while in illustration.build(),
    #    but it might be more useful to have that done here. Not sure yet.
    def write(self, filename_stub=None, file_extesion="svg.in"):
        if not filename_stub:
            pass # write to the given filename if asked to...
        else:
            pass # otherwise, write to "{self.name}.svg.in"
             

class svgFileComponent():
    """Simple SVG component class for constituents that can be loaded directly from file.

    The original use case for this is the `right-arrow.svg` component, which is
    used in almost every illustration and (in the present understanding of things)
    needs to be identical in every case. Loading each instance from file reduces
    the need to regenerate a new, identical copy for every illustration.
    """
    def __init__(self,
                 name,
                 filepath):

        #from lxml import etree as ET # shouldn't be necessary; loads from package....
        #from pathlib import Path # shouldn't be necessary; loads from package....
        
        self.name = name

        # turn `filepath` into an absolute path
        print(f'[Component `{self.name}`]: Checking for the presence of external file: {filepath}', file=sys.stderr)
        p = Path(filepath)
        if p.exists():
            p = p.resolve()
            self.file = p
            print(f'[Component `{self.name}`]: ixternal file: {self.file} exists', file=sys.stderr)
        else:
            raise OSError(f'[Component `{self.name}`]: the font file {filepath} could not be located. Does {p} exist?')
        return None

    
    def generate(self):
        #from lxml import etree as ET # shouldn't be necessary; loads from package....
        namespace = "{http://www.w3.org/2000/svg}"

        print(f'[Component `{self.name}`], loading external file: {self.file}', file=sys.stderr)
        with open(self.file, 'r+t', encoding='utf-8') as svgfile:
            self.tree = ET.parse(svgfile)
            self.root = self.tree.getroot()

        return ET.tostring(self.tree, encoding="unicode")

    
class Illustration():
    """An SVG illustration. Each illustration is defined in a YAML file that specifies some basic properties
       and, typically, a list of components that must be individually generated as intermediate images.

       For example, there is usually a "-before" and "-after" variant of a shaping cluster, which require two
       separate commands and parameter sets to generate. The two are then typically composited into the final
       illustration with an 'arrow' image in between to separate them.

       There are some exception to this formula, however:
       - single-component illustrations, which can be generated with a single command.
       - duplicates of other illustrations, which can be generated by making a file copy of the original illustration.
       """

    # TODO: Offer an optional "write intermediate files" function, which would
    # be used to generate all of the component (e.g. -before.svg / -after.svg) files,
    # although I think it'd be better to name them something like `foo-before.svg.in`.
    #
    # The reason being that, by NOT naming the intermediates .svg, we can easily have
    # the Makefile compare the modification times of the .yaml files and the final .svg
    # files, and rebuild any that exhibit some changes.
    #
    # That might also be wise to check for the font files, but I'm less certain how to
    # implement that.
    #

    # TODO: take a `buildroot` variable, and construct all font-file paths doggedly from that.
    # Print thw Path.cwd() to the user feedback to remind / log where it is running and help
    # debug surprises.
    #
    # That will push all responsiblity for providing paths to the font files up the stack
    # into the actual build script. Likely that means we can dispense with the FONTDIR stuff
    # entirely within the code, which is a major plus.
    #
    # We need: YAML `font` key -> file path
    #          ??? -> output directory for writing (same as YAML directory?)
    #          intermediate files???
    def __init__(self, dirbase, configfile=None):
        from pathlib import Path

        if not dirbase:
            raise ValueError(f'Illustration instantiation is missing the required `dirbase` argument.')
        else:
            self.dirbase = Path(dirbase)
        
        if configfile:
            with open(configfile, 'r') as infile:
                config = yaml.safe_load(infile)

                if "SOLE_COMPONENT" in config and "components" in config:
                    # Do safety checks before creating anything....
                    # Safety check; `SOLE_COMPONENTS` can't coexist with other formats
                    raise ValueError("Illustration cannot be a SOLE_COMPONENT and contain any other defined components")

                if "name" in config:
                    self.name = config.get("name")
                    print(f'[{self.name}]: Configuration file found...', file=sys.stderr)
                else:
                    raise ValueError("Illustration configuration file must include a name for the illustration.")
                
                #self.source = None # Is this attribute deprecated / dead now?

                if "generator" in config:
                    self.generator = config.get("generator")
                elif "GENERATOR" in config:
                    self.generator = config.get("GENERATOR") # *** deprecated key name !!!!
                else:
                    self.generator = "hb-view"

                if "font" in config:
                    # handle FONTDIR ... at least somewhat
                    #self.font = config.get("font").replace("FONTDIR", FONTDIR)
                    
                    print(f'[{self.name}]: Found font key = {config.get("font")}...', file=sys.stderr)
                    fontp = self.dirbase / config.get("font")
                    
                    print(f'[{self.name}]: Font path = {fontp}...', file=sys.stderr)
                    fontp = fontp.resolve()
                elif "FONT" in config:
                    # handle FONTDIR ... at least somewhat
                    #self.font = config.get("FONT").replace("FONTDIR", FONTDIR) # *** deprecated key name !!!!
                    fontp = self.dirbase / config.get("FONT")
                    fontp = fontp.resolve()
                else:
                    self.font = None

                # The config-file tests allow creating an Illustration with an empty .font attribute.
                # We are here treating the case where a .font was listed in the config file but can't
                # be found differently. Empty .font attribute is OK; bad .font attribute is an exception.
                #
                # I don't know if that's the right way, long-term; it just permits some testing.
                if fontp:
                    if fontp.exists():
                        self.font = str(fontp)
                    else:
                        raise OSError(f'[{self.name}] Instantiation issue: cannot resolve the file path for the `font` parameter in {configfile}')

                # Optional fill color, defaults to black
                self.basecolor = config.get("basecolor", "000000")
            
                # Optional list of CSS color classes to assign
                # to <use> elements in output
                self.cssclasses = config.get("cssclasses", [])
                    
                # Optional "build intermediate files" option, from method arguments
                self.build_intermediates = False
                    
                # Check if we need to build duplicate copies
                if "duplicates" in config:
                    self.duplicates = config["duplicates"]
                else:
                    self.duplicates = []

                if "SOLE_COMPONENT" in config:
                    # Instantiate a single svgComponent
                    #
                    # we will need to handle 'file:' components separately here
                    #
                    self.components = [svgComponent(self.name,
                                                    self.font,
                                                    config.get("unicodes", None),
                                                    config.get("fontsize", None),
                                                    config.get("margin", None),
                                                    config.get("features", None),
                                                    config.get("options", None),
                                                    self.generator,
                                                    self.basecolor
                                                    )]
                    self.layout = "solo"

                elif "components" in config:
                    self.components = []
                    # Instantiate an svgComponent for each one; 
                    # we will need to handle 'file:' components separately here
                    for component in config["components"]:
                        for key in component.keys():
                            component_name = key
                            component_structure = component[key]
                            if "file" in component_structure:

                                print(f'[{self.name}]: Found external-file key = {component_structure.get("file")}...', file=sys.stderr)
                                filep = self.dirbase / component_structure.get("file")
                    
                                print(f'[{self.name}]: File path = {filep}...', file=sys.stderr)
                                filep = filep.resolve()

                                self.components.append(svgFileComponent(component_name, filep))
                            else:
                                self.components.append(svgComponent(component_name,
                                                                    self.font,
                                                                    component_structure.get("unicodes", None),
                                                                    component_structure.get("fontsize", None),
                                                                    component_structure.get("margin", None),
                                                                    component_structure.get("features", None),
                                                                    component_structure.get("options", None),
                                                                    self.generator,
                                                                    self.basecolor # TODO: use .get() here in case of overrides
                                                                    ))
                    self.layout = "horizontal"

                return None
            
        else:
            print(f'[{self.name}]: No configuration file found; initializing emtpy Illustration object', file=sys.stderr)
            self.name = None
            self.generator = "hb-view"
            self.font = None
            self.components = []
            self.basecolor = "000000"
            #self.source = None # Is this attribute deprecated / dead now?
            self.cssclasses = []
            self.duplicates = []
            self.build_intermediates = False
            self.layout = None

            return None

        
    def build(self):
        """Build the illustration, and populate self.data with the result.

        This method iterates through all of the consitutent svgComponents that
        make up the illustration, generating each (or loading it directly from
        an external file), then concatenates them into a single SVG.

        The resulting SVG representation is held in self.data as plain text (UTF-8).
        It is not exported to file; you must call .write() for that, after
        optionally updating the CSS classes of the constituent parts with
        .apply_css_classes().

        The .build() method *does* automatically set the viewBox to the correct
        width and height required to show all elements; this is necessary because
        some glyph-generating recipes produce elements that extend beyond (or are
        fully outside) of the original bounding box (e.g., mark positioning for
        non-spacing marks: the mark glyph, when attached, may lie outside of the
        base glyph's bounding box, and the SVGs are generally set to the base
        glyphs' bounding boxes).
        """
        
        svgs = []
        self.data = None
        
        print(f'Building {self.name}...', file=sys.stderr)
        if not self.components:
            raise ValueError(f'[{self.name}]: No component definitions were found.')
        else:
            print(f'[{self.name}]: Iterating through components...', file=sys.stderr)
            for component in self.components:
                # Build each component by calling its own .generate()
                svgs.append(component.generate())
                    
        if svgs:
            if self.layout == "solo":
                # Only one component; no layout work is required
                print(f'[{self.name}]: Completing solo layout for the single-component illustration.', file=sys.stderr)
                self.data = svgs[0]
            elif self.layout == "horizontal":
                # Multiple components; need to concatenate
                import io                           
                import svg_stack as ss

                # Use io.StringIO as a substitute file-like object, because
                # svg_stack.Document.save() will only write to file-like
                # things.
                with io.StringIO("") as outbuffer:
                    doc = ss.Document()
                    layout1 = ss.HBoxLayout()

                    print(f'[{self.name}]: Starting horizontal layout for the illustration.', file=sys.stderr)
                    for svg in svgs:
                        # Use io.BytesIO as a file-like substitute... svg_stack will
                        # try to load the file-like object via lxml, and lxml complains
                        # about io.StringIO objects....
                        print(f'adding SVG to layout', file=sys.stderr)
                        layout1.addSVG(io.BytesIO(bytes(svg, 'utf-8')), alignment=ss.AlignCenter)
                        print(f'added SVG to layout', file=sys.stderr)

                    print(f'adding layout to document', file=sys.stderr)
                    doc.setLayout(layout1)
 
                    print(f'[{self.name}]: Completing horizontal layout for the illustration.', file=sys.stderr)
                    doc.save(outbuffer)
                    self.data = outbuffer.getvalue()
                                 
            else:
                raise NotImplementedError(f'[{self.name}]: Unknown composite layout requested. Only `solo` and `horizontal` are supported.')
                             
        else:
            raise ValueError(f'[{self.name}]: After the component-generation step, no SVG elements were found.')
 
                 
        # With the raw SVG elements created and (if needed) concatenated into one,
        # compute and apply a viewBox to self.data
        print(f'[{self.name}]: Applying viewbox to the illustration.', file=sys.stderr)
        if not self.data:
            raise ValueError(f'[{self.name}]: No SVG elements were found in the illustration.')
        else:
            # Ugly, but works for the moment. All SVGs from hb-view and svg_stack use this namespace string....
            namespace = "{http://www.w3.org/2000/svg}"
            #tree = ET.parse(self.data)
            tree = ET.ElementTree(ET.fromstring(self.data))
            root = tree.getroot()
 
            # This nsmap stuff can probably be removed; we could then remove lxml
            # from the build requirements....
            d = root.nsmap
            #print(d)
            #del d[None]
            #d["svg"] = namespace[1:-1]
            #print(d)
            #print(root.tag)
 
            # Check whether or not this is an SVG tree that we know how to work with
            if (root.tag != namespace + "svg"):
                print(f'[{self.name}]: Parsing trouble; it\'s unclear if this is a compatible SVG', file=sys.stderr)
                raise ValueError(f'Root element: {root.tag}')
            else:
                if ("width" in root.attrib) and ("height" in root.attrib):
                    # copy the width and height into a new viewBox
                    # assign "100%" as the new width and remove the height attribute
                    if ("viewBox" in root.attrib):
                        print(f'[{self.name}]: Unexpected: perhaps this SVG already has a viewBox?', file=sys.stderr)
                        raise ValueError("viewBox is; ", root.attrib["viewBox"])
                    else:
                        w = root.attrib["width"]
                        h = root.attrib["height"]
                        root.attrib["viewBox"] = "0 0 " + w + " " + h
                        root.attrib["width"] = "100%"
                        root.attrib.pop("height")
 
                        # Paste the updated tree back to self.data ... as a string, since it was before ??
                        self.data = ET.tostring(tree, encoding="unicode")
                else:
                    print(f'[{self.name}]: Unexpected: this SVG is missing width or height attributes?', file=sys.stderr)
                    raise ValueError(f'Width: {root.attrib["width"]}, Height: {root.attrib["height"]}')
             
         
        # apply cssclasses to self.data
        # ...maybe we should make that a feature that needs to be called explicitly, so we can test
        # the SVG component generation, etc, regardless of whether we know (or even have) CSS classes/colors
        return None
 
     
    # Can / should this be an instance property?
    #
    # I don't know why I'd need a getter... maybe to extract them for the YAML?
    #
    # I think making this a function will make it easier
    # to skip this step for PDF (or other noninteractive)
    # output formats.
    def apply_css_classes(self, classlist=None):
        """Assign the provided CSS classes to the <use> elements in the illustration.
 
        This method updates the SVG data in self.data, by assigning a CSS class from
        `classlist`, in the order found, to the <use> elements in the SVG.
 
        As of now, all SVG images generated by hb-view and svg_stack are structured so
        that the top-level shapes are rendered into the viewport through a <use> element.
        Consequently, CSS and JavaScript can only affect the appearance of the shapes
        through these <use>s.
        """
        # Change of thought; we don't start out with any classes at all, so we don't need to check
        # for the presence of all of the possibilities. Perhaps we'll need to for some future SVG
        # component generator, but for now we can just add the ones requested in self.cssclasses.
         
        print(f'[{self.name}]: Applying CSS classes to the <use> elements in the illustration.', file=sys.stderr)
 
        if not classlist:
            classlist = self.cssclasses
             
        if not self.data:
            raise ValueError(f'[{self.name}]: The illustration does not contain SVGs in its .data attribute;'
                             'it must be built before CSS classes can be assigned.')
        else:
            # Check the length of the classlist
            u_count = self.data.count("<use ")
            c_count = len(classlist)
            if u_count != c_count:
                raise ValueError(f'[{self.name}]: Mismatched CSS-class count. Found {u_count} <use> elements but {c_count} CSS classes were provided.')
            else:
                # Ugly, but works for the moment. All SVGs from hb-view and svg_stack use this namespace string....
                namespace = "{http://www.w3.org/2000/svg}"
                #tree = ET.parse(self.data)
                tree = ET.ElementTree(ET.fromstring(self.data))
                root = tree.getroot()
 
                # This nsmap stuff can probably be removed; we could then remove lxml
                # from the build requirements....
                d = root.nsmap
                #print(d)
                #del d[None]
                #d["svg"] = namespace[1:-1]
                #print(d)
                #print(root.tag)
 
                # Check whether or not this is an SVG tree that we know how to work with
                if (root.tag != namespace + "svg"):
                    print(f'[{self.name}]: Parsing trouble; it\'s unclear if this is a compatible SVG', file=sys.stderr)
                    raise ValueError(f'Root element: {root.tag}')
                else:
                    # iterate through the entire tree
                    elems = list(root.iter())
                    for elem in elems:
                        # inserting a generic 'class=""' into each <use> element
                        if (elem.tag == namespace + "use"):
                            if ("class" not in elem.attrib):
                                # TODO: support a user-supplied class attribute, either directly
                                #       or via a class list for the whole file, which we
                                #       would then store in the docs.
                                # TODO: append to the class, rather than replacing it.
                                #       Not sure how duplicate classes would be handled by ETree....
                                elem.attrib["class"] = classlist.pop(0)
                                print(elem.tag, elem.attrib["class"])
                            else:
                                # We should pass pre-existing class attributes through, not considering them errors
                                print(f'[{self.name}]: Unexpected: encountered a <use> element with non-empty classes', file=sys.stderr)
                                raise NotImplementedError(f'{elem.tag} has CSS classes: {elem.attrib["class"]}')
 
                    # Paste the updated tree back to self.data ... as a string, since it was before ??
                    self.data = ET.tostring(tree, encoding="unicode")
                 
        return None
 
     
    def prepend_elementIDs(self, svg_data, id_prefix):
        """Insert a prefix into the ID of  each SVG element, to ensure uniqueness.
 
        This function is meant to guarantee that every SVG and all of that SVGs child
        elements has an ID attribute that is unique within the entire document. The
        uniqueness is mandatory because the SVG images are inlined into the HTML file
        output: any elements that share a non-unique ID would all be affected by CSS
        and JavaScript simultaneously, because all inline SVG elements belong to the
        single, shared namespace/DOM of the HTML page.
 
        The inlining itself is mandatory because CSS and JavaScript cannot modify SVG
        objects that are included on the HTML page as external <img src="foo"> elements.
        Or, at least, not reliably, and not with most browsers.
        """
        print(f'[{self.name}]: Inserting "{id_prefix}" prefixes to the ID attributes of all elements in the illustration.', file=sys.stderr)
 
        if not svg_data:
            raise ValueError(f'[{self.name}]: The illustration does not contain SVGs in its .data attribute;'
                             'it must be built before CSS classes can be assigned.')
        if not id_prefix:
            raise ValueError('No ID prefix was supplied.')
         
        # Ugly, but works for the moment. All SVGs from hb-view and svg_stack use this namespace string....
        namespace = "{http://www.w3.org/2000/svg}"
        # Load the SVG string from a variable, not a file. In lxml.ETree, that means
        # you also have to wrap the result in a new ElementTree, because for some reason
        # loading from a string returns a root, but loading the same thing from file
        # returns a tree....
        tree = ET.ElementTree(ET.fromstring(svg_data))
        root = tree.getroot()
 
        # This nsmap stuff can probably be removed; we could then remove lxml
        # from the build requirements....
        d = root.nsmap
        #print(d)
        #del d[None]
        #d["svg"] = namespace[1:-1]
        #print(d)
        #print(root.tag)
 
        # Check whether or not this is an SVG tree that we know how to work with
        if (root.tag != namespace + "svg"):
            print(f'[{self.name}]: Parsing trouble; it\'s unclear if this is a compatible SVG', file=sys.stderr)
            raise ValueError(f'Root element: {root.tag}')
        else:
            if ("id" not in root.attrib):
                # insert id_prefix as the id for the complete SVG
                #print(f'[{self.name}]: no pre-existing #id', file=sys.stderr)
                root.attrib["id"] = id_prefix
            else:
                # Need to make these actual exceptions
                print(f'[{self.name}]: Unexpected: this SVG root element already has an id!', file=sys.stderr)
                raise ValueError(f'Root id is: {root.attrib["id"]}')
                 
            # iterate through the entire tree
            elems = list(root.iter())
            for elem in elems:
                # ... prepending id_prefix to all id declarations
                if elem != root:
                    if "id" in elem.attrib:
                        print(f'[{self.name}]: {elem.tag} old id = {elem.attrib["id"]}', file=sys.stderr)
                        old_id = elem.attrib["id"]
                        if old_id[0:1] != "id":
                            elem.set("id", id_prefix + ":" + old_id)
                            print(f'[{self.name}]: Element {elem.tag}, new id: {elem.attrib["id"]}', file=sys.stderr)
                        else:
                            print(f'[{self.name}]: Error: {elem.tag} has unexpected id: {elem.attrib["id"]}', file=sys.stderr)
                            raise ValueError(f'Element id found = {elem.attrib["id"]}')
                     
                    # ... prepending id_prefix to all id hrefs
                    if ( "{" + d["xlink"] + "}" + "href" in elem.attrib):
                        print(f'[{self.name}]: Xlink element {elem.tag}, assigning id to target', file=sys.stderr)
                        old_target = elem.attrib["{" + d["xlink"] + "}" + "href"]
                        # sample::
                        #       before prepend:
                        #                      <use xlink:href="#glyph0-1" 
                        #        after prepend:
                        #                      <use xlink:href="#bengali-ccmp:id2:glyph-0-1"
                        # TODO: test whether the following syntax (which is used to access the xlink href)
                        #       also gets written out correctly to the file.
 
                        if old_target[1:2] != "id":
                            elem.set("{" + d["xlink"] + "}" + "href", "#" + id_prefix + ":" + old_target[1:])
                            print(f'[{self.name}]: {elem.attrib}', file=sys.stderr)
                        else:
                            print(f'[{self.name}]: Unexpected, element {elem.tag} has unexpected target: {old_target}', file=sys.stderr)
 
        # Return the altered SVG as a string, since it's intended to be written to file
        return ET.tostring(tree, encoding="unicode")
 
 
    def write(self, filename_stub=None):
        """Write the illustration to an SVG file, using the supplied filename stub.
 
        This will also write out any requested duplicate illustrations into their own
        SVG files, using the filename stubs found in the `duplicates` block in the
        YAML configuration file for the primary illustration."""
        print(f'[{self.name}]: Writing SVG content out to files', file=sys.stderr)
 
        if not filename_stub:
            filename_stub = self.name
         
        if not self.data:
            raise ValueError(f'[{self.name}]: Writing to file: the illustration does not contain SVGs in its .data attribute;'
                             'it must be built before it can be written out to file.')

        # Regardless of whether there are or are not any duplicates (as tested below), 
        # apply element IDs to self.data, using the unaltered name, then write that out
        # to file.
        # Here, as elsewhere, we probably don't need to update self.data. Doing so might
        # save a few cycles if we were writing again and again, but that's not the use case.
        with open(filename_stub + ".svg", 'w+t', encoding="utf-8") as outfile:
            print(f'[{self.name}]: Writing SVG content out to file {filename_stub}.svg', file=sys.stderr)
            outfile.write( self.prepend_elementIDs(self.data, filename_stub) )
 
        # Handle all requested image duplicates.
        if self.duplicates:
            # Create a copy for each entry in the self.duplicates list
            for duplicate in self.duplicates:                
                # Apply distinct element IDs to self.data, using 'duplicate' instead of
                # filename_stub.
                # Make an ET.tree for each duplicate, apply the ID, write it to
                # its own file, but don't overwrite that ET.tree back into self.data
                with open(duplicate + ".svg", 'w+t', encoding="utf-8") as outfile:
                    print(f'[{self.name}]: Writing SVG content out to duplicate illustration {duplicate}.svg', file=sys.stderr)
                    outfile.write( self.prepend_elementIDs(self.data, duplicate) )
                     
        return None
     
 
    # Can / should this be an instance property?
    #
    # I don't know why I'd need a getter... maybe to extract them for file writing
    def set_name(self, new_name):
        """Insert the provided new_name as the prefix token
           for all necessary elements."""
        # I think making this a function will make it easier
        # to generate duplicates when necessary
        self.name = new_name
        return None


def extract_color_classes(filename):
    """Extracts an ordered list of the color classes in an SVG file."""
    from lxml import etree as ET
 
    namespace = "{http://www.w3.org/2000/svg}"
         
    with open(filename, 'r+t', encoding='utf-8') as svg:
        tree = ET.parse(svg)
        root = tree.getroot()
 
        d = root.nsmap
        if (root.tag != namespace + "svg"):
            raise Exception("Parsing trouble; it's unclear if the SVG file is compatible.")
        else:
            cssclasses = []
            elems =  list(root.iter())
            for elem in elems:
                if (elem.tag == namespace + "use"):
                    if "class" in elem.attrib:
                        cssclasses.append(elem.attrib["class"])
                    else:
                        print(f'Warning: found <use> element with no classes: {elem}', file=sys.stderr)
 
    return cssclasses
